### ISSUE TITLE
Error when trying to upload a simple json file to create a stack (AWS)

### ISSUE THREAD

**Issue by aladdinskastle** [linuxacademy/content-aws-csa2019#3]
![error creating a new stack from lesson file](https://user-images.githubusercontent.com/54381127/63475870-4c64b780-c444-11e9-9746-d21e27c4df77.jpg)
![error creating a new stack from lesson file_2ndscreenshot](https://user-images.githubusercontent.com/54381127/63475871-4c64b780-c444-11e9-9f35-4268cd608511.jpg)

**Comment by acantril** [comment]
Hi - I've just tested this and it works without issues?
Can you confirm if you are saving the file from the github web interface are you saving the 'RAW' version - otherwise you are saving a web page.

**Comment by acantril** [comment]
The file actually has 5 lines ... so the fact it says like 615 suggests its not the correct 'file' you are using.

**Comment by aladdinskastle** [comment]
Thanks Adrian!

I received the file (.json) from a set of lesson files as part of an online
training I’m taking. You are correct, it only have 5 lines or so - which is
why I couldn’t understand the error. My guess is the file itself corrupted
(?) or just needs to be updated (?)...

**Comment by aladdinskastle** [comment]
Would you happen to have the file you used when you attempted?

**Comment by acantril** [comment]
So if you go here https://github.com/linuxacademy/content-aws-csa2019/blob/master/lesson_files/01_aws_sa_fundamentals/introduction_to_cloudformation/s3bucket.json .. and then click the RAW button it loads this URL https://raw.githubusercontent.com/linuxacademy/content-aws-csa2019/master/lesson_files/01_aws_sa_fundamentals/introduction_to_cloudformation/s3bucket.json and thats the one which i used :)

**Comment by acantril** [comment]
I'm the instructor of that training btw :) assuming you are accessing this via the linuxacademy course ?

**Comment by acantril** [comment]
If you ever save files in that way, use the raw version.
or a better way, click this https://github.com/linuxacademy/content-aws-csa2019 and then the 'clone or download button' and then download a ZIP .. it will give you all the files for the course :)

**Comment by aladdinskastle** [comment]
Thank you Adrian! I will re-try.
